name: devops-prj-02-devops-exoplanet

on:
  [push]
    #pull_request:
        #branches: [main]

jobs:
    check_code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.6.0
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: 16.14
            - run: npm ci
            - run: npm run lint
            - run: npm run prettier
            - run: npm test